### ISSUE TITLE
file a bug

### ISSUE THREAD

**Issue by tea513** [axsddlr/wombo_bot#2]
in generator.py 

        r = session.get("https://app.wombo.art/api/tasks/" + task_id, headers=auth_headers)
        data = r.json()

        #data["state"]   Sometimes kererror occurs, I checked it, and the value of "state" does not exist
        state = data["state"]

        if state == "completed":
            break
        if state == "failed":
            print(data)
            raise RuntimeError(data)

I changed it to this

        data = r.json()
        if "state" in data:
            state = data["state"]

            if state == "completed":
                break
            if state == "failed":
                print(data)

                raise RuntimeError(data)

        if ("state" in data) == False:
            return

**Comment by axsddlr** [comment]
thanks for the info. fixed
